name: Python CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov  # Explicitly installing pytest and pytest-cov

    - name: Run Code Linting (Flake8)
      run: python -m flake8 . --max-line-length=88  # Using python -m to call flake8 for compatibility

    - name: Run Unit Tests and Coverage Report
      run: python -m pytest --cov=app  # Using python -m pytest to prevent command issues

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: .coverage
